### ISSUE TITLE
[Invalid]: Switch to Plain CSS with Tailwind

### ISSUE THREAD

**Issue by onissen** [ncs-northware/northware#141]
### Beschreibe das Problem

Da Tailwind Sass nicht standardmäßig unterstützt und das Compiling immer lange dauert, möchte ich wieder zu CSS wechseln und möglichst nur noch normales Tailwind verwenden. Dazu nehme ich mir den Code des [Examples von Turborepo](https://github.com/vercel/turborepo/tree/main/examples/with-tailwind) zu Hilfe

**Comment by onissen** [comment]
## Todo

- [ ] Rebiuld tailwind-config Package-File and go through packages
- [ ] Define Tailwind Config Files everywhere it is used in and go through packages
- [ ] Insert tailwind through `globals.css`, remove `globals.sass`
- [ ] Rethink `_*.sass` code
