### ISSUE TITLE
[Add]: Typescript Support

### ISSUE THREAD

**Issue by onissen** [ncs-northware/northware#142]
### Was ist der Plan?

Ich möchte Typescript verwenden. Das ermöglicht ein besseres Developing und wird Type-Safe. Außerdem kann shadcn Code dann besser kopiert werden.

### Weitere Beschreibungen

Neben den Umstellungen der `.jsx`-Dateien auf `.tsx` muss Typescript konfiguriert werden. Dazu sollte es Shareable Configs geben.

- [Turborepo Example-Package config-typescript](https://github.com/vercel/turborepo/tree/main/examples/with-tailwind/packages/config-typescript)
- [tsconfig Package von openstatus](https://github.com/openstatusHQ/openstatus/tree/main/packages/tsconfig)
- [next-forge/typescript-config Package](https://github.com/haydenbleasel/next-forge/tree/main/packages/typescript-config)

**Comment by onissen** [comment]
## Todo

- [ ] Einführung `@northware/tsconfig` Package
- [ ] Typdeklarationen Fehler in den `@northware` Packages
- [ ] Umstellung Auth Package, `middleware.js`, `route.js`
- [ ] Umstellung `next.config.mjs`
- [ ] Umstellung `postcss.config.mjs`
- [ ] Umstellung tailwind.config.js in App, UI, Config
- [ ] Implementierung von TypeScript Checks als globaler Command bzw. Turborepo Task und Einbindung in `localci` und Turbo CI

**Comment by onissen** [comment]
`@northware/eslint-config` und alle implementierenden Config-Dateien müssen aktuell nicht auf TypeScript umgestellt werden bevor das komplette Package neu gedacht wird.
