### ISSUE TITLE
[Add]: New Workflows

### ISSUE THREAD

**Issue by onissen** [ncs-northware/northware#19]
### Was ist der Plan?

Ich möchte einige neue GitHub Actions Workflows hinzufügen

**Comment by onissen** [comment]
## Tasks on Workflows

- [x] Pull Request Labeler
- [x] Projekt Workflows in Northware New
- [x] Turborepo CI
- [x] autofix.ci
- [ ] Dependabot

**Comment by onissen** [comment]
- [ ] Ich möchte nochmal über den Turborepo CI nachdenken.  Macht der test Command überhaupt etwas, oder muss dafür Jest konfiguriert werden?

**Comment by onissen** [comment]
- [ ] Kann der autofix.ci Workflow in Turborepo CI integriert werden, damit dieser nicht immer abgebrochen wird?

**Comment by onissen** [comment]
> * [ ]  Ich möchte nochmal über den Turborepo CI nachdenken.  Macht der test Command überhaupt etwas, oder muss dafür Jest konfiguriert werden?

Wird in #65 weiterverfolgt
