### ISSUE TITLE
[Add]: Coding Conventions

### ISSUE THREAD

**Issue by onissen** [ncs-northware/northware#45]
### Was ist der Plan?

Es müssen Regelungen gefunden werden, wie Entwickler das Coding ausführen sollen. Dazu braucht es eine Doku, Commit-Templates usw.

### Tasks

- [x] [Conventional Commits](https://www.conventionalcommits.org/de/v1.0.0/)
- [x] Child Branch PRs
- [x] Branch Protection
- [x] Benennung von Branches

**Comment by onissen** [comment]
Strapi nutzt [commitlint](https://commitlint.js.org) um Conventional Commits umzusetzen.
